name: Post JSON File

on:
  push:
    branches:
      - main  # Runs when you push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data
        run: |
          curl -X POST "https://:Xde__oTrTDu8WShr37CL-A@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:lBFGaNe_QP2PV6aQW1IqxQ/streams/AQAAAKaTIEL42EjfhGI2G1mDsGUAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
